export {default as Header} from './header/Header'
export {default as Feed } from './feed/Feed'
export {default as Side} from './side/Side'
export {default as Trends} from './trends/Trends'
export {default as Footer} from './footer/Footer'
export {default as MobileMenu} from './mobileMenu/MobileMenu'
export {default as UserProfile} from './userProfile/UserProfile'